fix loop mode when argument contains single quotes
When the ruler-extension with the loop mode was runned and the filter argument had a single quote, this error occurs :
```
Error: Context reference \test1\\ does not exists.
```

cf https://github.com/atoum/ruler-extension/issues/15

This occurs because there was too much escaping when running the loop mode :

```
/usr/bin/php5 -f ./vendor/bin/atoum -- --disable-loop-mode --force-terminal -f 'toto_test.php' --filter ''\\''test1'\\'' in tags' --score-file '/tmp/atoum.score'
```

Now the command launched by the loop mode is properly escaped :
```
/usr/bin/php5 -f ./vendor/bin/atoum -- --disable-loop-mode --force-terminal -f 'toto_test.php' --filter ''\''test1'\'' in tags' --score-file '/tmp/atoum.score'
```